---
- name: Install Docker on Ubuntu
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure apt cache is up-to-date
      ansible.builtin.apt:
        update_cache: yes
      retries: 3
      delay: 10
      register: apt_update
      until: apt_update is succeeded

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      retries: 3
      delay: 10
      register: apt_install_prereqs
      until: apt_install_prereqs is succeeded

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker
        state: present

    - name: Ensure Docker service is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
